In [34]:
import numpy as np
import pandas as pd
from pathlib import Path

In [35]:
super_data_cleaned = pd.read_csv("Resources/super_data_cleaned.csv")
combined_madness = pd.read_csv("Madness_Data/Combined_Madness.csv")

In [36]:
combined_madness

,Unnamed: 0,Rank,Team,GM,W-L,FGM,FGA,FG%,Madness,Years
0,0,44.0,North Carolina (ACC),6.0,6-0,171.0,394.0,43.4,1.0,16-17
1,1,45.0,Gonzaga (WCC),6.0,5-1,147.0,346.0,42.5,1.0,16-17
2,2,32.0,South Carolina (SEC),5.0,4-1,136.0,299.0,45.5,1.0,16-17
3,3,19.0,Oregon (Pac-12),5.0,4-1,137.0,288.0,47.6,1.0,16-17
4,4,38.0,Kentucky (SEC),4.0,3-1,108.0,244.0,44.3,1.0,16-17
...,...,...,...,...,...,...,...,...,...,...
685,685,14.0,Iona (MAAC),1.0,0-1,31.0,64.0,48.4,1.0,15-16
686,686,13.0,Fresno St. (Mountain West),1.0,0-1,26.0,53.0,49.1,1.0,15-16
687,687,9.0,Cincinnati (AAC),1.0,0-1,28.0,55.0,50.9,1.0,15-16
688,688,3.0,Southern California (Pac-12),1.0,0-1,28.0,52.0,53.8,1.0,15-16
689,689,2.0,Michigan St. (Big Ten),1.0,0-1,30.0,54.0,55.6,1.0,15-16

In [37]:
super_data_cleaned

,Unnamed: 0,Team,Years,AST,TO,Ratio,TPG,3FG%,PTS,PPG,ORebs,DRebs,REB,RPG,FGM,FGA,FG%,FT,FTA,FT%
0,5,Creighton (Big East),13-14,614,342,1.80,9.771429,41.4,"2,756",78.7,293,899,"1,192",0.00,957,"1,927",49.7,486,654,74.3
1,6,Iowa St. (Big 12),13-14,663,380,1.74,10.555556,35.8,"2,989",83.0,375,"1,012","1,387",0.00,"1,062","2,239",47.4,564,814,69.3
2,7,UCLA (Pac-12),13-14,636,379,1.68,10.243243,38.0,"3,003",81.2,368,940,"1,308",0.00,"1,073","2,196",48.9,628,839,74.9
3,8,Iona (MAAC),13-14,576,349,1.65,10.575758,39.6,"2,760",83.6,288,806,"1,094",0.00,947,"1,944",48.7,528,739,71.4
4,9,Georgia St. (Sun Belt),13-14,451,275,1.64,8.088235,37.5,"2,641",77.7,280,794,"1,074",0.00,900,"1,923",46.8,589,757,77.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3706,3711,Siena (MAAC),23-24,342,505,0.68,15.781250,28.0,"1,934",60.4,375,757,"1,132",35.38,702,"1,758",39.9,361,541,66.7
3707,3712,VMI (SoCon),23-24,335,507,0.66,15.843750,31.2,"2,204",68.9,299,871,"1,170",36.56,818,"1,935",42.3,358,517,69.2
3708,3713,Alabama A&M (SWAC),23-24,369,565,0.65,16.142857,28.7,"2,414",69.0,394,854,"1,248",35.66,806,"1,918",42.0,654,906,72.2
3709,3714,Mississippi Val. (SWAC),23-24,271,495,0.55,15.967742,29.2,"1,719",55.5,298,613,911,29.39,613,"1,611",38.1,350,532,65.8
3710,3715,Coppin St. (MEAC),23-24,240,455,0.53,15.689655,28.3,"1,678",57.9,283,590,873,30.10,585,"1,571",37.2,355,489,72.6

In [38]:
safe = super_data_cleaned.Years.unique()
[print(x)for x in safe]

13-14
14-15
15-16
16-17
17-18
18-19
19-20
20-21
21-22
22-23
23-24

[None, None, None, None, None, None, None, None, None, None, None]

In [39]:
empty_data = pd.DataFrame()

In [40]:
for year in safe:
    df = super_data_cleaned[super_data_cleaned['Years'] == year].sort_values(by=['PTS'], ascending=False)
    top_150 = df.head(150)
    empty_data = pd.concat([empty_data, top_150])

In [41]:
empty_data

,Unnamed: 0,Team,Years,AST,TO,Ratio,TPG,3FG%,PTS,PPG,ORebs,DRebs,REB,RPG,FGM,FGA,FG%,FT,FTA,FT%
33,38,VMI (Big South),13-14,491,371,1.32,10.600000,32.5,"3,089",88.3,503,949,"1,452",0.00,"1,088","2,441",44.6,600,842,71.3
2,7,UCLA (Pac-12),13-14,636,379,1.68,10.243243,38.0,"3,003",81.2,368,940,"1,308",0.00,"1,073","2,196",48.9,628,839,74.9
29,34,Louisiana Tech (CUSA),13-14,582,424,1.37,11.459459,32.9,"2,998",81.0,478,970,"1,448",0.00,"1,034","2,284",45.3,644,948,67.9
15,20,Louisville (),13-14,568,391,1.45,10.567568,36.8,"2,998",81.0,503,893,"1,396",0.00,"1,051","2,232",47.1,608,920,66.1
215,220,Kentucky (SEC),13-14,446,481,0.93,12.025000,33.2,"2,992",74.8,574,"1,034","1,608",0.00,"1,004","2,214",45.3,781,"1,146",68.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3534,3539,Northern Ky. (Horizon),23-24,456,407,1.12,12.333333,31.9,"2,470",74.8,347,794,"1,141",34.58,882,"1,935",45.6,497,691,71.9
3529,3534,Presbyterian (Big South),23-24,426,377,1.13,11.424242,33.4,"2,469",74.8,312,787,"1,099",33.30,897,"1,901",47.2,465,701,66.3
3379,3384,Yale (Ivy League),23-24,495,316,1.57,9.575758,35.1,"2,465",74.7,326,879,"1,205",36.52,919,"1,969",46.7,386,546,70.7
3697,3702,SFA (WAC),23-24,422,530,0.80,16.060606,33.4,"2,463",74.6,393,791,"1,184",35.88,849,"1,890",44.9,562,796,70.6
3392,3397,Cornell (Ivy League),23-24,544,366,1.49,12.200000,34.8,"2,463",82.1,287,776,"1,063",35.43,895,"1,836",48.7,363,502,72.3

In [43]:
balanced_data = empty_data

In [44]:
merged_data = combined_madness.merge(balanced_data, left_on=['Team','Years'], right_on=['Team','Years'], how='right')

In [45]:
merged_data

,Unnamed: 0_x,Rank,Team,GM,W-L,FGM_x,FGA_x,FG%_x,Madness,Years,...,ORebs,DRebs,REB,RPG,FGM_y,FGA_y,FG%_y,FT,FTA,FT%
0,NaN,NaN,VMI (Big South),NaN,NaN,NaN,NaN,NaN,NaN,13-14,...,503,949,"1,452",0.00,"1,088","2,441",44.6,600,842,71.3
1,151.0,15.0,UCLA (Pac-12),3.0,2-1,85.0,180.0,47.2,1.0,13-14,...,368,940,"1,308",0.00,"1,073","2,196",48.9,628,839,74.9
2,NaN,NaN,Louisiana Tech (CUSA),NaN,NaN,NaN,NaN,NaN,NaN,13-14,...,478,970,"1,448",0.00,"1,034","2,284",45.3,644,948,67.9
3,148.0,38.0,Louisville (),3.0,2-1,68.0,157.0,43.3,1.0,13-14,...,503,893,"1,396",0.00,"1,051","2,232",47.1,608,920,66.1
4,138.0,20.0,Kentucky (SEC),6.0,5-1,148.0,317.0,46.7,1.0,13-14,...,574,"1,034","1,608",0.00,"1,004","2,214",45.3,781,"1,146",68.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,NaN,NaN,Northern Ky. (Horizon),NaN,NaN,NaN,NaN,NaN,NaN,23-24,...,347,794,"1,141",34.58,882,"1,935",45.6,497,691,71.9
1646,NaN,NaN,Presbyterian (Big South),NaN,NaN,NaN,NaN,NaN,NaN,23-24,...,312,787,"1,099",33.30,897,"1,901",47.2,465,701,66.3
1647,368.0,37.0,Yale (Ivy League),2.0,1-1,44.0,106.0,41.5,1.0,23-24,...,326,879,"1,205",36.52,919,"1,969",46.7,386,546,70.7
1648,NaN,NaN,SFA (WAC),NaN,NaN,NaN,NaN,NaN,NaN,23-24,...,393,791,"1,184",35.88,849,"1,890",44.9,562,796,70.6
1649,NaN,NaN,Cornell (Ivy League),NaN,NaN,NaN,NaN,NaN,NaN,23-24,...,287,776,"1,063",35.43,895,"1,836",48.7,363,502,72.3

In [46]:
df_filled = merged_data.fillna(0)

In [47]:
df_filled

,Unnamed: 0_x,Rank,Team,GM,W-L,FGM_x,FGA_x,FG%_x,Madness,Years,...,ORebs,DRebs,REB,RPG,FGM_y,FGA_y,FG%_y,FT,FTA,FT%
0,0.0,0.0,VMI (Big South),0.0,0,0.0,0.0,0.0,0.0,13-14,...,503,949,"1,452",0.00,"1,088","2,441",44.6,600,842,71.3
1,151.0,15.0,UCLA (Pac-12),3.0,2-1,85.0,180.0,47.2,1.0,13-14,...,368,940,"1,308",0.00,"1,073","2,196",48.9,628,839,74.9
2,0.0,0.0,Louisiana Tech (CUSA),0.0,0,0.0,0.0,0.0,0.0,13-14,...,478,970,"1,448",0.00,"1,034","2,284",45.3,644,948,67.9
3,148.0,38.0,Louisville (),3.0,2-1,68.0,157.0,43.3,1.0,13-14,...,503,893,"1,396",0.00,"1,051","2,232",47.1,608,920,66.1
4,138.0,20.0,Kentucky (SEC),6.0,5-1,148.0,317.0,46.7,1.0,13-14,...,574,"1,034","1,608",0.00,"1,004","2,214",45.3,781,"1,146",68.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1645,0.0,0.0,Northern Ky. (Horizon),0.0,0,0.0,0.0,0.0,0.0,23-24,...,347,794,"1,141",34.58,882,"1,935",45.6,497,691,71.9
1646,0.0,0.0,Presbyterian (Big South),0.0,0,0.0,0.0,0.0,0.0,23-24,...,312,787,"1,099",33.30,897,"1,901",47.2,465,701,66.3
1647,368.0,37.0,Yale (Ivy League),2.0,1-1,44.0,106.0,41.5,1.0,23-24,...,326,879,"1,205",36.52,919,"1,969",46.7,386,546,70.7
1648,0.0,0.0,SFA (WAC),0.0,0,0.0,0.0,0.0,0.0,23-24,...,393,791,"1,184",35.88,849,"1,890",44.9,562,796,70.6
1649,0.0,0.0,Cornell (Ivy League),0.0,0,0.0,0.0,0.0,0.0,23-24,...,287,776,"1,063",35.43,895,"1,836",48.7,363,502,72.3

In [48]:
df_clean = df_filled.drop({"Unnamed: 0_x", "Rank", "FG%_y", "GM", "W-L", "FGM_x", "FGA_x", "FG%_x", "Unnamed: 0_y"}, axis=1)
df_clean.head(50)

,Team,Madness,Years,AST,TO,Ratio,TPG,3FG%,PTS,PPG,ORebs,DRebs,REB,RPG,FGM_y,FGA_y,FT,FTA,FT%
0,VMI (Big South),0.0,13-14,491,371,1.32,10.600000,32.5,"3,089",88.3,503,949,"1,452",0.0,"1,088","2,441",600,842,71.3
1,UCLA (Pac-12),1.0,13-14,636,379,1.68,10.243243,38.0,"3,003",81.2,368,940,"1,308",0.0,"1,073","2,196",628,839,74.9
2,Louisiana Tech (CUSA),0.0,13-14,582,424,1.37,11.459459,32.9,"2,998",81.0,478,970,"1,448",0.0,"1,034","2,284",644,948,67.9
3,Louisville (),1.0,13-14,568,391,1.45,10.567568,36.8,"2,998",81.0,503,893,"1,396",0.0,"1,051","2,232",608,920,66.1
4,Kentucky (SEC),1.0,13-14,446,481,0.93,12.025000,33.2,"2,992",74.8,574,"1,034","1,608",0.0,"1,004","2,214",781,"1,146",68.2
5,Iowa St. (Big 12),1.0,13-14,663,380,1.74,10.555556,35.8,"2,989",83.0,375,"1,012","1,387",0.0,"1,062","2,239",564,814,69.3
6,BYU (WCC),1.0,13-14,544,395,1.38,11.285714,35.5,"2,931",83.7,463,969,"1,432",0.0,"1,012","2,186",730,"1,055",69.2
7,Belmont (OVC),0.0,13-14,571,463,1.23,12.861111,39.2,"2,876",79.9,315,808,"1,123",0.0,983,"1,973",587,794,73.9
8,UConn (AAC),1.0,13-14,488,457,1.07,11.425000,38.7,"2,873",71.8,387,"1,009","1,396",0.0,971,"2,162",644,829,77.7
9,Michigan St. (Big Ten),1.0,13-14,637,440,1.45,11.578947,39.2,"2,870",75.5,409,991,"1,400",0.0,"1,024","2,159",515,728,70.7
10,Baylor (Big 12),1.0,13-14,563,440,1.28,11.578947,38.6,"2,843",74.8,525,931,"1,456",0.0,959,"2,109",645,947,68.1
11,Fresno St. (Mountain West),0.0,13-14,470,394,1.19,10.102564,35.7,"2,837",72.7,359,961,"1,320",0.0,950,"2,170",646,884,73.1
12,Mercer (ASUN),1.0,13-14,586,420,1.40,11.666667,38.4,"2,836",78.8,407,931,"1,338",0.0,982,"2,061",582,791,73.6
13,Louisiana (Sun Belt),0.0,13-14,472,467,1.01,13.342857,36.7,"2,835",81.0,483,852,"1,335",0.0,988,"2,127",613,913,67.1
14,Wisconsin (Big Ten),1.0,13-14,468,307,1.52,8.078947,37.6,"2,793",73.5,337,929,"1,266",0.0,927,"2,018",642,861,74.6
15,Oregon (Pac-12),1.0,13-14,492,389,1.26,11.441176,38.9,"2,783",81.9,356,804,"1,160",0.0,928,"1,977",668,865,77.2
16,Delaware (CAA),1.0,13-14,377,334,1.13,9.542857,34.7,"2,782",79.5,385,879,"1,264",0.0,936,"2,108",658,925,71.1
17,Purdue Fort Wayne (Summit League),0.0,13-14,524,440,1.19,12.222222,39.3,"2,774",77.1,377,838,"1,215",0.0,975,"1,979",539,813,66.3
18,New Mexico St. (WAC),1.0,13-14,474,457,1.04,12.694444,37.1,"2,771",77.0,428,918,"1,346",0.0,936,"1,918",705,"1,027",68.6
19,Arizona (Pac-12),1.0,13-14,574,387,1.48,10.184211,36.4,"2,769",72.9,465,984,"1,449",0.0,996,"2,123",573,870,65.9
20,Kansas (Big 12),1.0,13-14,523,463,1.13,13.228571,34.0,"2,764",79.0,416,920,"1,336",0.0,955,"1,937",665,935,71.1
21,Gonzaga (WCC),1.0,13-14,525,419,1.25,11.638889,39.7,"2,761",76.7,343,948,"1,291",0.0,972,"1,963",562,793,70.9
22,Iona (MAAC),0.0,13-14,576,349,1.65,10.575758,39.6,"2,760",83.6,288,806,"1,094",0.0,947,"1,944",528,739,71.4
23,Creighton (Big East),1.0,13-14,614,342,1.80,9.771429,41.4,"2,756",78.7,293,899,"1,192",0.0,957,"1,927",486,654,74.3
24,Duke (ACC),1.0,13-14,509,334,1.52,9.542857,39.5,"2,745",78.4,424,783,"1,207",0.0,929,"2,020",571,783,72.9
25,Michigan (Big Ten),1.0,13-14,525,345,1.52,9.324324,40.2,"2,736",73.9,329,831,"1,160",0.0,945,"1,982",527,691,76.3
26,Radford (Big South),0.0,13-14,460,383,1.20,10.942857,36.2,"2,729",78.0,397,816,"1,213",0.0,972,"2,035",564,820,68.8
27,Oklahoma St. (Big 12),1.0,13-14,463,356,1.30,10.470588,36.4,"2,728",80.2,332,871,"1,203",0.0,898,"1,941",693,964,71.9
28,Florida (SEC),1.0,13-14,509,431,1.18,11.051282,35.9,"2,727",69.9,450,935,"1,385",0.0,945,"2,056",582,871,66.8
29,Arkansas (SEC),0.0,13-14,521,392,1.33,11.529412,36.2,"2,723",80.1,404,818,"1,222",0.0,928,"2,105",614,846,72.6
30,Minnesota (Big Ten),0.0,13-14,528,444,1.19,11.684211,35.2,"2,715",71.4,394,888,"1,282",0.0,918,"2,053",607,818,74.2
31,Wichita St. (MVC),1.0,13-14,491,374,1.31,10.388889,35.1,"2,706",75.2,419,963,"1,382",0.0,896,"1,941",664,916,72.5
32,Oklahoma (Big 12),1.0,13-14,483,376,1.28,11.393939,37.9,"2,704",81.9,398,844,"1,242",0.0,909,"2,034",601,802,74.9
33,Toledo (MAC),0.0,13-14,509,346,1.47,10.176471,34.5,"2,694",79.2,421,797,"1,218",0.0,929,"1,995",643,887,72.5
34,Iowa (Big Ten),1.0,13-14,532,371,1.43,11.242424,35.0,"2,689",81.5,446,885,"1,331",0.0,919,"1,984",660,898,73.5
35,ETSU (ASUN),0.0,13-14,429,408,1.05,11.657143,36.3,"2,689",76.8,368,859,"1,227",0.0,879,"2,045",656,877,74.8
36,Northwestern St. (Southland),0.0,13-14,513,420,1.22,13.548387,33.4,"2,686",86.6,394,789,"1,183",0.0,958,"2,037",594,802,74.1
37,Eastern Ky. (OVC),1.0,13-14,498,359,1.39,10.558824,39.0,"2,677",78.7,243,641,884,0.0,881,"1,810",600,798,75.2
38,Tennessee (SEC),1.0,13-14,472,388,1.22,10.486486,32.5,"2,672",72.2,501,923,"1,424",0.0,927,"2,048",613,852,71.9
39,Dayton (Atlantic 10),1.0,13-14,485,442,1.10,11.945946,37.7,"2,671",72.2,414,875,"1,289",0.0,935,"2,018",558,819,68.1
40,Canisius (MAAC),0.0,13-14,425,394,1.08,11.588235,38.6,"2,661",78.3,384,752,"1,136",0.0,913,"1,989",564,762,74.0
41,SFA (Southland),1.0,13-14,574,393,1.46,11.228571,34.5,"2,661",76.0,451,735,"1,186",0.0,922,"1,992",569,800,71.1
42,Southeast Mo. St. (OVC),0.0,13-14,533,419,1.27,13.093750,35.9,"2,654",82.9,360,831,"1,191",0.0,961,"1,924",514,743,69.2
43,Villanova (Big East),1.0,13-14,523,406,1.29,11.941176,35.6,"2,651",78.0,379,884,"1,263",0.0,870,"1,907",607,848,71.6
44,Sam Houston (Southland),0.0,13-14,550,447,1.23,12.771429,39.2,"2,647",75.6,417,803,"1,220",0.0,875,"1,893",647,969,66.8
45,Murray St. (OVC),0.0,13-14,446,420,1.06,12.352941,37.6,"2,647",77.9,397,836,"1,233",0.0,901,"1,898",593,883,67.2
46,Ohio (MAC),0.0,13-14,559,475,1.18,12.837838,35.3,"2,647",71.5,351,947,"1,298",0.0,937,"2,042",499,699,71.4
47,Georgia St. (Sun Belt),0.0,13-14,451,275,1.64,8.088235,37.5,"2,641",77.7,280,794,"1,074",0.0,900,"1,923",589,757,77.8
48,Towson (CAA),0.0,13-14,355,415,0.86,11.527778,35.7,"2,633",73.1,433,962,"1,395",0.0,867,"1,910",686,997,68.8
49,VCU (Atlantic 10),1.0,13-14,459,428,1.07,12.228571,34.9,"2,624",75.0,492,825,"1,317",0.0,922,"2,196",520,772,67.4

In [49]:
df_clean["Madness"].value_counts()

Madness
0.0    1060
1.0     590
Name: count, dtype: int64

In [50]:
# Write combined DataFrame to CSV
df_clean.to_csv('madness_label.csv', index=False)